### ISSUE TITLE
SC7-Pilot Sextant to Image-Aggregator

### ISSUE THREAD

**Issue by gioargyr** [big-data-europe/README#1]
Hi, i would like to  ask how can we achieve the connection between Sextant and ImageAggregator. 
Sextant needs Image-Aggregator's url/port to achieve requests to Image-Aggregator.
Sextant is always up and running in UoA's servers while Image-Aggregator is dockerized and runs inside NCSR's cluster whenever we tell it to do so.

**Comment by gmouchakis** [comment]
This can be achieved by forwarding the port Image-Aggregator is using through nginx running on the bdegw machine. Please provide the cluster internal IP and the port you want to be forwarded and we will configure ngnix accordingly.
By the way I would expect that Sextant will also be deployed in the cluster since it is supposably a core component of BDE. Is there any particular reason that I am not aware of for using UoA's servers instead?

**Comment by gioargyr** [comment]
Whether the Sextant will run as a docker NCSR-cluster or always up and running in UoA's server, as far as I know is still debatable.
I guess that the sooner we take the decision, the sooner we can setup the connections, so I will inform you immediately when the decision is taken.
Thanks.

**Comment by gioargyr** [comment]
Hi! We deployed Sextant as a docker in the NCSR-cluster. After many attempts and tests to connect it with image-aggregator we ended up that it was feasible only when both the dockers ran in the same node and Sextant connected to "localhost:<image-aggregator_exposed-port>".
I tested all the cases where Sextant tried to connect with image-aggregator(IA) to:
IA_host-IP : IA_exposed-port
IA_real-IP : IA_real-port
localhost : IA_exposed-port
imageaggregator : IA_exposed-port   ("imageaggregator" named the service, container_name and hostname of image-aggregator)
All the tests took place having Sextant and IA running either on the same or on different nodes.
In every case both the dockers were running in the same network(bde_net).
Do you believe that we are doing something wrong and we achieve the connection only by running both the dockers in the same node?
How SemaGrow can communicate with Strabon while running on different nodes?

**Comment by madnificent** [comment]
Could it be that Sextant only accepts connections from localhost?  I'm not sure how to configure it, but it could be that tomcat doesn't accept connections from anything but localhost.  Could you check whether this is the case?

**Comment by zefyros** [comment]
Hello, this is George Stamoulis,

It is not Sextant's issue. From what I saw the two tomcat installations in the different dockers cannot communicate through the tunneled ports. The http GET request from Sextant is refused by the tomcat server where imageaggregator is located. I suspect it has to do with tomcat settings. Even when you use nc command to test the connection with the imageaggregator you get refused. Maybe it has to do with the firewall? Are you using proxys?

**Comment by gmouchakis** [comment]
@zefyros 

> From what I saw the two tomcat installations in the different dockers cannot communicate through the tunneled ports 

how do you use "tunneled ports"? Are you referring to Sextant located in UoA and ImageAggregator in NCSR or to both services running in containers in NCSR docker swarm cluster?

I don't know how Sextant and ImageAggregator work but I also suspect that you have to properly configure Tomcat inside the container. There is no firewall or proxy between the containers. If they are both part of the same overlay network in docker swarm they should be able to communicate with each other.

**Comment by gioargyr** [comment]
Hi! We are referring to Sextant and ImageAggregator as a dockers that run in NCSR docker swarm cluster.
In every test both the dockers were running in the same network (bde_net).

**Comment by gmouchakis** [comment]
This issue was related with the way Sextant and ImageAggragator were configured to communicate and is not related with the BDE platform.
