### ISSUE TITLE
tab for auto-complete is not working

### ISSUE THREAD

**Issue by gioargyr** [big-data-europe/README#5]
Hi all,
I am using NCSR-D cluster and  the last half an hour whenever I press "tab" for auto-complete in terminal of master node I get the following message: "cannot create temp file for here-document: No space left on device".
I just checked and every other node works fine.
fyi: http://unix.stackexchange.com/questions/277387/bash-cannot-create-temp-file-for-here-document-no-space-left-on-device

**Comment by gmouchakis** [comment]
I cleared up some disk space and it works now.
