### ISSUE TITLE
bde_net not found

### ISSUE THREAD

**Issue by gioargyr** [big-data-europe/README#6]
Hi again!
When I try to run a docker and attach it to bde_net I get the following error:
"Error response from daemon: Error response from daemon: network bde_net not found."
I run everything with the same commands I did yesterday, so there's no possibility of bad commands.

**Comment by gmouchakis** [comment]
Because the disk was full (https://github.com/big-data-europe/README/issues/5), for some reason, swarm lost the networks. I recreated the networks, deployed some test containers in the bde_net and it works now.
