### ISSUE TITLE
KV store to support Swarm

### ISSUE THREAD

**Issue by gmouchakis** [big-data-europe/README#8]
In the Installation section we are currently using the progrium/consul container as KV store backend. This container uses an old version of Consul (v0.4.0) and Swarm supports Consul version 0.5.1 or higher (https://docs.docker.com/swarm/discovery/). Also this version along with the concept of using a KV store deployed in a container to support Swarm caused a lot of problems during our tests because if the container or the docker engine fails then the whole Swarm is not usable anymore. In the NCSR cluster we are currently using Zookeeper installed natively and it is far more reliable than using progrium/consul.

We support multiple ways to deploy the platform (using docker machine, manual installation, ansible will be added soon) and the result should be the same in all cases so I propose to change the installation instructions and use Zookeeper installed natively.

**Comment by madnificent** [comment]
Can we go with an installation that runs in a Docker?  This limits the amount of requirements to get the platform up and running. The benefit of Consul is that it runs in a Docker.  Either a docker installation of Zookeeper, or an updated version of Consul seem more optimal to me.  @earthquakesan your opinion?

**Comment by gmouchakis** [comment]
@madnificent in the Manual Installation guide we provide instructions for Ubuntu 14.04. The installation of Zookeeper in Ubuntu 14.04 is pretty straight forward:
`apt-get install -y zookeeper zookeeper-bin zookeeperd`
and you get a Zookeeper server running and listening on `zk://node_ip:2181`

Instructions on how to install Zookeeper outside the repos are also pretty simple (https://zookeeper.apache.org/doc/r3.1.2/zookeeperStarted.html). You have to download the tar, create a simple `conf/zoo.cfg` like 
```
tickTime=2000
dataDir=/srv/zookeeper
clientPort=2181
```
and finally run `bin/zkServer.sh start`

All guides I've seen so far use a natively installed KV store and those using `proprium/consul` are deprecated.
